### ISSUE TITLE
PyQt5 support

### ISSUE THREAD

**Issue by mfitzp** [hlamer/qutepart#21]
It would be nice to have PyQt5 support for this widget for my application.

I contributed to the support in matplotlib for PySide, PyQt4 and PyQt5 and would suggest a similar approach, namely:

* move Qt imports to a qt.py shim file in the root, and have each file import from there
* in the shim handle the incompatibilities between Qt4 and Qt5 (module rearrangements) in either direction (i.e. to either make Qt4 look like Qt5 or vice versa).

If you'd be interested in adding the support for this I'm happy to do it and submit a PR for the completed code?

Thanks,

**Comment by rapgro** [comment]
Future development support for Qt4 is going to be discontinued shortly with the final version 4.8.7 release.
Please notice: http://blog.qt.io/blog/2015/05/26/qt-4-8-7-released/

**Comment by rapgro** [comment]
Qt5 works with current master. Can we close this issue?
