### ISSUE TITLE
Unit test hang

### ISSUE THREAD

**Issue by bjones1** [hlamer/qutepart#28]
When I execute ``run_all.py``, all tests pass but the program never quits; I have to kill the process manually. (This is on Windows). Investigating, I can remove all tests except for test_vim.py and still get the hang. Looking at older revisions, this happens back to ba77ebb8ad89e9ab502afec1a605c6ae33252602 (again, with only test_vim.py). Before that, I get syntax errors (del_ is now named terminate). If I run test_vim.py directly, there's no hang; running ``run_all.py`` (which only executes test_vim.py, since I've deleted all other tests) produces the hang. ???

**Comment by hlamer** [comment]
Seems to be fixed Now
