### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by rapgro** [hlamer/qutepart#30]
Are there any plans to support Python 3?
Please notice https://docs.python.org/dev/howto/pyporting.html

Some script snippet like the following is needed to migrate.
```
sed -i -r 's,(print) (.*),\1(\2),' setup.py
find qutepart -name \*.py |xargs sed -i 's,unicode,str,' 
```

**Comment by hlamer** [comment]
`2to3` does the job better, than sed.

Check `py3` branch, it is not well-tested but could work.

**Comment by rapgro** [comment]
Thanks for the quick reply. I didn't know about the py3 branch and will test it. Nice, there's also Qt5 support.

**Comment by hlamer** [comment]
I'd like to switch enki and Qutepart to Py3 and Qt5 in a few month and abandon Py2 and Qt4.

**Comment by rapgro** [comment]
There's a closing bracket missing at end of line 86.
https://github.com/hlamer/qutepart/blob/py3/setup.py#L86

**Comment by hlamer** [comment]
Thanks, fixed!
