### ISSUE TITLE
Unit test hang

### ISSUE THREAD

**Issue by bjones1** [hlamer/qutepart#36]
Unless I delete `test/test_api.py` and `test/test_bracket_hilighter.py`, the tests hang. When I press Ctrl+C on a hang, I see:

```
C:\Users\bjones\Documents\enki_all\qutepart\tests>python run_all.py
test_1 (test_actions.Print) ... skipped 'Does not work'
test_jump (test_bookmarks.Test) ... ok
test_set_with_keyboard (test_bookmarks.Test) ... ok
test_set_with_mouse (test_bookmarks.Test) ... skipped 'Crashes Qt'
test_1 (test_bracket_hlighter.Test) ... ok
test_click_selects_first (test_completion.Test) ... skipped 'Crashes Qt 4.8.3'
test_down_selects_first (test_completion.Test) ... Traceback (most recent call l
ast):
  File "run_all.py", line 9, in <module>
    unittest.TextTestRunner(verbosity=2).run(suite)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\unittest\runner.py", line 168, in run
    test(result)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\unittest\case.py", line 625, in __call__
    return self.run(*args, **kwds)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\unittest\case.py", line 577, in run
    testMethod()
  File "C:\Users\bjones\Documents\enki_all\qutepart\tests\test_completion.py", l
ine 34, in test_down_selects_first
    self.app.processEvents()
KeyboardInterrupt
```

So, it seems like the Windows Qt works a bit differently than Linux in terms of processing events. I'll play with this when I can...

**Comment by hlamer** [comment]
It could be Py3/Qt5 problem. For me Qutepart tests pass but Enki freezes randomly

**Comment by bjones1** [comment]
Ah, I see. Hopefully, that will help us find some tricky bugs still hiding in the code. But it sounds like a hard bugs to track down...

**Comment by bjones1** [comment]
Looking, I found that the line `self._document.contentsChange.connect(self._onContentsChange)` in `qutepart.syntaxhilighter.SyntaxHilighter` caused the hang, even if the `_onContentsChange` does nothing (by replacing its contents with a `pass`). Adding a decorator in 4c6c2b5fc503191eb9c583ede585327aeb499968 fixed it. 

This connects a native signal to a Python slot, where the slot has one extra default argument than the signal. Removing the extra argument also makes the test stop hanging (thought this of course causes lots of failures).

There seem to be some subtle cases when a missing `pyqtSlot` decorator causes Qt/PyQt to act in unexpected ways.

This was tested using [WinPython 3.4.3.7Qt5](https://winpython.github.io/).

**Comment by hlamer** [comment]
Thanks!
I hope same strategy will help fixing other freezes
