### ISSUE TITLE
Window build notes

### ISSUE THREAD

**Issue by bjones1** [hlamer/qutepart#37]
This "issue" is more a log of the problems I encountered trying to build in Windows. I'm building on Python 3.4 x64. I think most of the pain is caused by the requirement of using Visual Studio 2010 on Windows 10. When binaries for PyQt5 are available for Python 3.5, this should be much easier, since Python 3.5 uses a modern compiler (Visual Studio 2015).

Determine compiler to build with
=========================
To determine what compiler was used to build CPython, and therefore what compiler should be used to build an extension, just run Python.

```
C:\Users\bjones\Documents\enki_all\qutepart>python
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AM
D64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

See http://stackoverflow.com/questions/70013/how-to-detect-if-im-compiling-code-with-visual-studio-2008 for a list of values to match with compiler versions.

Wrong compiler detected
====================
An earlier Python 2.7 installation (Pythonx,y) provides an installed Microsoft Visual C++ 2008. Python finds that and complains by default.]:

```
C:\Users\bjones\Documents\enki_all\qutepart>python setup.py install --include-di
r=../pcre2-10.10/build --lib_dir=../pcre2-10.10/build/Release
Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    if not _checkDependencies():
  File "setup.py", line 64, in _checkDependencies
    if not compiler.has_function('rand', includes=['stdlib.h']):
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\distutils\ccompiler.py", line 791, in has_function
    objects = self.compile([fname], include_dirs=include_dirs)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\distutils\msvc9compiler.py", line 460, in compile
    self.initialize()
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\distutils\msvc9compiler.py", line 371, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall
    return unpatched['query_vcvarsall'](version, *args, **kwargs)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
    raise ValueError(str(list(result.keys())))
```

The solution: run Python from a `Visual Studio Command Prompt (2010)` (see the Start menu). 

Failing test builds
================
Next, the build complains that test builds fail:

```
C:\Users\bjones\Documents\enki_all\qutepart>\Users\bjones\Downloads\WinPython-64
bit-3.4.3.7Qt5\python-3.4.3.amd64\python.exe setup.py install --include-dir=../p
cre-8.37/build --lib-dir=../pcre-8.37/build/Release
randulkyuaoe.c

Users\bjones\AppData\Local\Temp\a.out.exe.manifest : general error c1010070: Fai
led to load and parse the manifest. The system cannot find the file specified.
It seems like C compiler is not installed or not operable.
```

Solution: use the `--force` option.

```
C:\Users\bjones\Documents\enki_all\qutepart>\Users\bjones\Downloads\WinPython-64
bit-3.4.3.7Qt5\python-3.4.3.amd64\python.exe setup.py install --include-dir=../p
cre-8.37/build --lib-dir=../pcre-8.37/build/Release --force
```

64-bit compiler not installed
========================
Next, building an extension with the default Visual Studio 2010 Express tool set fails.

```
C:\Users\bjones\Documents\enki_all\qutepart>\Users\bjones\Downloads\WinPython-64
bit-3.4.3.7Qt5\python-3.4.3.amd64\python.exe setup.py install --include-dir=../p
cre-8.37/build --lib-dir=../pcre-8.37/build/Release --force
running install
running bdist_egg

..snip...

C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo
 /INCREMENTAL:NO /LIBPATH:../pcre-8.37/build/Release /LIBPATH:C:\Users\bjones\Do
wnloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\libs /LIBPATH:C:\Users\bjo
nes\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\PCbuild\amd64 pcre.l
ib /EXPORT:PyInit_cParser build\temp.win-amd64-3.4\Release\qutepart/syntax/cPars
er.obj /OUT:build\lib.win-amd64-3.4\qutepart\syntax\cParser.pyd /IMPLIB:build\te
mp.win-amd64-3.4\Release\qutepart/syntax\cParser.lib /MANIFESTFILE:build\temp.wi
n-amd64-3.4\Release\qutepart/syntax\cParser.pyd.manifest
python34.lib(python34.dll) : fatal error LNK1112: module machine type 'x64' conf
licts with target machine type 'X86'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\
link.exe' failed with exit status 1112
```

Solution: Install the 64-bit compiler. This isn't easy; just downloading and installing the  Windows 7 DSK fails. Instead, carefully follow http://www.mathworks.com/matlabcentral/answers/95039-why-does-the-sdk-7-1-installation-fail-with-an-installation-failed-message-on-my-windows-system.

Rebuild PCRE
-------------------
So, rebuild PCRE: `C:\Users\bjones\Documents\enki_all\pcre-8.37\build>"\Program Files (x86)\CMake\bin\cmake.exe"  cmake .. -DBUILD_SHARED_LIBS:BOOL=OFF -DPCRE_SUPPORT_UTF:BOOL=ON -DPCRE_SUPPORT_JIT:BOOL=ON -G "Visual Studio 10 2010 Win64`. Note the different compiler name.

The rebuild fails:

```
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\intrin.h(26): fa
tal error C1083: Cannot open include file: 'ammintrin.h': No such file or direc
tory [C:\Users\bjones\Documents\enki_all\pcre-8.37\build\pcre.vcxproj]
```

Compiler fix
----------------
Per a comment in https://connect.microsoft.com/VisualStudio/feedback/details/660584/, the overall order is:

(a) VS2010 C++ Express (in my case)
(b) SDK 7.1
(c) VS2010 SP1
(d) SP1 Compiler patch KB2519277

The previous link took care of (a) and (b). Installing (c), then a clean and rebuild of PCRE worked. However, trying to build from a `Visual Studio Command Prompr (2010)` fails, since this selects the x86 tools.

Environment fix
---------------------
Instead, open the `Windows SDK 7.1 Command Prompt`, then build qutepart there. This works.

**Comment by hlamer** [comment]
Strange items from  PyQt changelog:

```
changeset:   df9e3329a638
date:        Tue Sep 08 17:11:42 2015 +0100
Updates to installers for Python v3.5.

changeset:   8ab07055894e
date:        Tue Sep 08 10:21:55 2015 +0100
Use win32-msvc2015 for Python v3.5.
```

Maybe we should try to install PyQt on Python 3.5?

**Comment by bjones1** [comment]
It's not released yet, per https://riverbankcomputing.com/software/pyqt/download5. I *think* Phil Thompson is waiting for the release of Qt 5.6 to update the binaries. Per https://wiki.qt.io/Qt-5.6-release, that's on 9-Feb-2016, so I'd guess PyQt would follow in a few weeks. The alternative would be to compile PyQt5. Perhaps it would be easier than installing 64-bit MSVC 2010...

**Comment by bjones1** [comment]
I'm closing this for now. It's so much easier to just compile for 32-bit Python, and there's no reason to struggle with 64 bits. Hopefully, there will be an installer soon for Py3.5 that fixes this anyway.
