### ISSUE TITLE
Unit test crash

### ISSUE THREAD

**Issue by bjones1** [hlamer/qutepart#41]
On Windows, Py 3.4, Qt 5.5, 8f431f09bcab950b981a0f99af4b76acfb12c897, when running `python -m unittest -v test_syntax.test_rules.Test.test_dynamic_string_detect` and using the C parser, Python crashes. It's fine with the Python parser.

I think this has been present for a while -- I remember that in the past, all tests passed before I ran `python setup.py install ...`, then they would crash until I deleted `cPython.pyd`. But for some reason I didn't pay much attention...

**Comment by hlamer** [comment]
Reproduced on Linux

**Comment by hlamer** [comment]
Fixed!

**Comment by bjones1** [comment]
Nice job! That was fast! Looks good on Windows. I'll check on Mac when I can.
