### ISSUE TITLE
Qutepart Installation Bug Report 2

### ISSUE THREAD

**Issue by Aldenis2112** [hlamer/qutepart#54]
# Qutepart Installation Bug Report

On Windows 8.1, using Python 3.4.4 from the WinPython distribution, the following error occured while attempting to run `setup.py`. Upon further investigation, it was discovered that if a `--force` command was included in the setup command, it would install correctly.

This pull request therefore avoids a call `_checkDependencies` for Windows, achieving the same result as using `--force`.

### Output From Error:

```
C:\Users\Alden\Documents\GitHub\qutepart>python setup.py install --include-dir=.
./pcre-8.38/build --lib-dir=../pcre-8.38/build/Release
rand17owxxqo.c

Users\Alden\AppData\Local\Temp\a.out.exe.manifest : general error c1010070: Fail
ed to load and parse the manifest. The system cannot find the file specified.
It seems like C compiler is not installed or not operable.
```

**Comment by hlamer** [comment]
Fixed in #55
